name: Create Node.js Package

on:
  push:
    branches:
      - package

jobs:
  update-version:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm clean-install
      - run: npm audit signatures
      - run: > 
        npx 
          -p @semantic-release/changelog 
          -p @semantic-release/git 
          -p semantic-release 
          semantic-release --branches package

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

